### PR TITLE
digestmod=hashlib.md5 is requried for python3.8

### PR DESCRIPTION
**Pull request by Danielhiversen**
From python 3.8 docs

> Deprecated since version 3.4, will be removed in version 3.8: MD5 as implicit default digest for digestmod is deprecated. The digestmod parameter is now required. Pass it as a keyword argument to avoid awkwardness when you do not have an initial msg.

https://docs.python.org/3/library/hmac.html

### CODE REVIEW

**Comment by Danielhiversen** [comment]
@LinuxChristian

**Comment by LinuxChristian** [comment]
@Danielhiversen Thanks for the PR and the bump! GH didn't inform me of your PR for some reason. I do not really use the plugs anymore so it is great to see someone still does.

Everything looks fine to me on the deprecated warning but for the next time please disable your auto-linting tool (pyflake, black, auto-pep8). It makes it difficult to see what actually changed and what is just linting.

I will merge and release a new package. Do you use home-assistant? If so hass also need a version bump of the release. This will be v0.6.

**Comment by LinuxChristian** [comment]
https://github.com/LinuxChristian/pyW215/releases/tag/v0.6

**Comment by Danielhiversen** [comment]
Thanks, I will test 0.6 locally and then upgrade Home Assistant

**Comment by Danielhiversen** [comment]
Will you push it to pypi also?

**Comment by LinuxChristian** [comment]
https://pypi.org/project/pyW215/0.7.0/

The current release was already v0.6 (it just didn't have a GH release) so had to bump the version to v0.7.

**Pull request merged**
